<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View_nodeundefined_IFrame</name>
   <tag></tag>
   <elementGuidId>d12f09ce-7202-4605-a243-28cbadad816a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1029</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1029']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8b02dbf5-96af-4dbe-9327-81721537cbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-component-default</value>
      <webElementGuid>fdaab7fe-c22f-4525-81ce-6af5b18633f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1029</value>
      <webElementGuid>e3229071-9c11-4d95-933b-8e6b67c75700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeundefined_IFrame</value>
      <webElementGuid>ec36655c-b3a3-459d-9d05-c25353e00581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707372483663</value>
      <webElementGuid>bf3ec406-de9a-4f07-8dff-9a9594f69881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93da2d46-fd01-44dd-a3e5-4492e37baf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1029&quot;)</value>
      <webElementGuid>3e7c008a-1bc1-4206-bdee-6a2ab504bbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1029']</value>
      <webElementGuid>3d8318ba-d3a8-4efe-b7e4-9c19c202bbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nodeundefined-body']/iframe</value>
      <webElementGuid>85932d6f-c566-4478-8529-9b7b59026607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d204eeb5-88b4-4f34-b1bf-ec8eff55d10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1029' and @name = 'nodeundefined_IFrame' and @src = '/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707372483663']</value>
      <webElementGuid>3514e1eb-0f79-4860-a69a-497e70ad89a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
