<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Export Current Page</name>
   <tag></tag>
   <elementGuidId>7cf3a27d-1a4f-4122-9e59-fc0187c6e6c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnExport-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BtnExport-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd3837b2-9de1-4f5c-82ed-157eebfbb092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnExport-btnInnerEl</value>
      <webElementGuid>eaca2320-7ebe-47ed-9de0-c951d2e822b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>3a289226-3d3a-46ea-b451-f41e764a10a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c6857f3b-d127-4a43-9fc9-305256ddfc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>1db95d60-e780-42d2-bebe-73e3f7fec3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export Current Page</value>
      <webElementGuid>a7603ebd-f0c3-4614-bc3c-9dc47bdb4d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnExport-btnInnerEl&quot;)</value>
      <webElementGuid>9545deb0-b258-4320-a2ef-d94813a0d171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Export Data/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>c240bdff-28a4-4942-b296-7ee413d9d665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BtnExport-btnInnerEl']</value>
      <webElementGuid>b3b13025-f28d-41f9-844a-7a017e828dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='BtnExport-btnEl']/span[2]</value>
      <webElementGuid>df0c4881-ff33-4757-b288-b2b26b489543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export :'])[1]/following::span[6]</value>
      <webElementGuid>245cee99-b676-4329-9d2a-599419b4ebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Engineer Transaction'])[1]/following::span[10]</value>
      <webElementGuid>0ae7039a-77e3-4e96-9bc7-af05eed30398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export All Page'])[1]/preceding::span[2]</value>
      <webElementGuid>3cf0369f-be26-42d2-b984-129d65a778c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Record'])[1]/preceding::span[6]</value>
      <webElementGuid>426dbc38-9370-4656-84a0-d1b90ba0184f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export Current Page']/parent::*</value>
      <webElementGuid>77a777da-8045-416c-9a21-a929be8b4a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>fb5eb037-a452-453a-b6dd-d714783576d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BtnExport-btnInnerEl' and (text() = 'Export Current Page' or . = 'Export Current Page')]</value>
      <webElementGuid>24ffd8af-0e96-487a-a95b-a5dde38a817e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
