<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter_ContentPlaceHolder1_AdvancedFilt_ba1237</name>
   <tag></tag>
   <elementGuidId>45e91aa4-6652-4820-940d-fa64b15c42c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>304b9e5e-577e-4fd3-8f62-9a0470338882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker</value>
      <webElementGuid>aa20ad84-699b-49ff-9755-b35b5261b67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>1237ac45-4710-4cf1-8f23-cabd72baf734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ba044d59-00c2-4181-861f-6f89606cd2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker&quot;)</value>
      <webElementGuid>b50572a6-cae4-49e6-824d-e4b0097047e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Advanced Filter/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>ec4d9f26-7602-4f8c-b2f5-f9c75e1688af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      <webElementGuid>f410fecf-79ad-47d8-9ad8-d5533bfb088f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboField-triggerWrap']/div[3]</value>
      <webElementGuid>6891b9e8-ce7e-48c8-a676-544aaddcef9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>172acd2d-b640-4c30-bea5-ae73e2e94528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_AdvancedFilter1_cboField-trigger-picker']</value>
      <webElementGuid>0dd0bb52-4926-4d38-b6dc-5cb1942a08b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
