<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter_ContentPlaceHolder1_AdvancedFilt_9a2316</name>
   <tag></tag>
   <elementGuidId>cd1c2afe-9b6f-4d39-8482-c84373e0d63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[7]/div[2]/div[1]/div/div/div[1]/div/div/div/div/div/div[1]/div/div/div/div[3]/div[1]/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c9c91ed-4221-4bb8-811a-5306e0957770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker</value>
      <webElementGuid>2f96f72f-1a47-4c39-a7b4-244805710982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>d14e63e7-c564-4773-b198-99a5b9d0ffef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ea811c3c-545a-4e51-9c8a-1419a68e201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker&quot;)</value>
      <webElementGuid>64fd9731-6c4d-4c86-a8b0-27474bac2128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Advanced Filter/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>4fc20349-269e-4899-8ef2-bfedd66841cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker']</value>
      <webElementGuid>c6b62d41-7444-4411-91c8-4520ca6df9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-triggerWrap']/div[2]</value>
      <webElementGuid>11cd6426-7823-44a3-b0c2-5d989af6c79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>0c45af68-bd75-4ed0-91d7-ecf48afbf246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-trigger-picker']</value>
      <webElementGuid>692ad3fb-acdd-4d47-b9fb-ec07148f88e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
