<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View_nodeundefined_IFrame</name>
   <tag></tag>
   <elementGuidId>944b23c5-cf95-4acc-8bb8-edfe22f8713d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1029</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1029']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4cddd938-1d44-4b21-ab93-06d571834fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-component-default</value>
      <webElementGuid>a6d51fd6-9822-4c57-9bf1-6b7911c3cdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1029</value>
      <webElementGuid>459523d7-2505-462a-ba1b-2215a080683e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeundefined_IFrame</value>
      <webElementGuid>58ba2cb4-e478-42d2-8304-64d179c1fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707372806129</value>
      <webElementGuid>9bd8f5a8-f093-4172-86ce-da7cdd351ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82203bc5-3325-4e25-8431-b7ebd1f63175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1029&quot;)</value>
      <webElementGuid>10948a8a-df22-4c75-a146-62457086064f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1029']</value>
      <webElementGuid>a2c7e44a-7b1b-4ace-adcf-00cc39e15ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nodeundefined-body']/iframe</value>
      <webElementGuid>7aaaff97-0c63-442e-bd3d-250ec4bd6565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2b6124c5-4025-43c2-8972-2832b0981aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1029' and @name = 'nodeundefined_IFrame' and @src = '/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707372806129']</value>
      <webElementGuid>a833a62b-ba3f-4170-b964-85f39c6a8f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
