<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_ContentPlaceHolder1_AdvancedFi_f4e98b</name>
   <tag></tag>
   <elementGuidId>1351fd9a-27bc-4830-8c96-67be40c54222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d53d7db5-5aac-40e3-b3fc-5cda1eeada4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl</value>
      <webElementGuid>5128d91c-5f53-4035-805f-bcca62eef9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>97e70b3c-22c2-45da-8c67-1fcbb166e5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ff9b0fa-3419-460b-abed-deffe936523e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ba564484-9d1f-4f01-8427-66e3e07ddc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore</value>
      <webElementGuid>12b7add2-a602-4319-86bf-b23fa61a389a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98a735fd-45ed-44c1-a62b-219a2f8230ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6c619fb-3d18-4f5c-a2f8-7c572d90fca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e127035e-2ae7-4b8d-a1d7-59532d6bcc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d164d5f-23d4-4361-b1c7-57a9444e9186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef4ada70-e6e4-4371-b9c3-519d384683c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-ariaStatusEl</value>
      <webElementGuid>aea888c2-a0dd-4eef-a9e9-303cb15c8a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34f8c7de-2623-4615-84c1-4b8d1ce6b1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-text-default  x-form-empty-field x-form-empty-field-default x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>57ba0662-7652-43e2-b9c1-edd1e4592f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93602960-2130-43a6-995a-835b1113a729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore</value>
      <webElementGuid>39ecb8b8-9f55-499e-8e33-555da3732eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl&quot;)</value>
      <webElementGuid>75c1bba6-a3a1-442e-8837-3f90a8e6886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Advanced Filter/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>a7eab7c0-3d88-4e98-9f4e-6b61390f04cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl']</value>
      <webElementGuid>d7033ec8-538d-48fd-bcb7-4c6ad0009d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputWrap']/input</value>
      <webElementGuid>1276f936-9f70-4f96-946d-be491914f2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>dc70d2ed-4f10-44a1-9d25-c2f6bd21b985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore-inputEl' and @type = 'text' and @name = 'ContentPlaceHolder1_AdvancedFilter1_txtvaluebefore']</value>
      <webElementGuid>1c760801-62b4-48ea-8a61-3d00342be0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
