<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Contain</name>
   <tag></tag>
   <elementGuidId>421ba4e0-0ff7-4d9d-9a6f-42527709b47d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[7]/div[2]/div[1]/div/div/div[1]/div/div/div/div/div/div[1]/div/div/div/div[3]/div[1]/div/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-79</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>22cd648e-078b-4eb4-8d60-5d38556b9cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e8584db5-099f-4dac-b444-1b9712840f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2c0ad55f-376e-4646-ba4f-b1eba6806d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>225afbcc-f29c-4fdb-9af0-262e942aea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>76cf5422-be3b-410f-89da-14c31b377426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>37cb7142-55c6-49dd-a035-044412db3281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>c3f52dda-b382-427d-9387-2f0c39b85294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-picker</value>
      <webElementGuid>dad75d16-1928-4419-b959-5b620f6b6095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-79</value>
      <webElementGuid>668b1de5-e7db-4f82-b384-91ae95a549a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contain</value>
      <webElementGuid>7efdce7c-0895-4a56-a135-a916abda5d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-79&quot;)</value>
      <webElementGuid>7dfb3c6d-31af-484c-be5b-fdc6848b8244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Advanced Filter/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>a1cf152e-b9b0-4499-953a-b961193e460d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-79']</value>
      <webElementGuid>02206c98-c007-47fd-a8aa-64f73439b76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ContentPlaceHolder1_AdvancedFilter1_cboFilterClause-picker-listEl']/li[3]</value>
      <webElementGuid>7dcf8e56-2cb9-4a45-bbd7-5b9dd0d2ae0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Equal'])[1]/following::li[1]</value>
      <webElementGuid>f01f3086-ad50-49e5-9fbd-f8c2a9d41ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equal'])[1]/following::li[2]</value>
      <webElementGuid>b376229c-6aed-4b37-9064-cdd4e5d85944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Doesn', &quot;'&quot;, 't Contain')])[1]/preceding::li[1]</value>
      <webElementGuid>5064cfbf-fb7b-4dc7-aece-8c3fbf67a8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start With'])[1]/preceding::li[2]</value>
      <webElementGuid>42e9e3a5-f712-4668-843f-0f49ed3d0fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contain']/parent::*</value>
      <webElementGuid>3a271af1-5f58-46ae-8af3-0a91555c7430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/ul/li[3]</value>
      <webElementGuid>31c11437-8da1-4071-bfce-91a3963f7d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-79' and (text() = 'Contain' or . = 'Contain')]</value>
      <webElementGuid>0f15c194-e3a9-4e4d-a913-823a1d38fefa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
