<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>ad5feac4-656c-49f6-ba8f-497fc76757a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84648fda-f5b6-48ae-9860-388799690995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl</value>
      <webElementGuid>7b077df1-21ec-43c3-a755-600177fd5c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>7ed5bc1c-c801-4871-a3ef-46a5e189fa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1a8881ba-b2e1-4bad-9ab4-66d27eb12284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-small</value>
      <webElementGuid>e842bf9a-1c4f-49f3-9b78-fc3b0bdd8731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>78bd40c8-f968-4087-994e-0be1ada55f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl&quot;)</value>
      <webElementGuid>466c48dd-3ac3-46ed-8cd7-fd0e8f7386f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Advanced Filter/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>091bfa1f-11d3-48d0-910f-31e02a0230db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl']</value>
      <webElementGuid>419c73d2-67b9-42b2-a2a6-71a6a633bebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnEl']/span[2]</value>
      <webElementGuid>4e0a7b29-c4c0-4e31-a39b-c4ee67154a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected date format d-m-Y.'])[2]/following::span[14]</value>
      <webElementGuid>3fbcd493-f186-443b-bdbc-65dec5e3ac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected date format d-m-Y.'])[1]/following::span[19]</value>
      <webElementGuid>b59cf3f1-b49c-40e5-941d-0e2fcb5218fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/preceding::span[2]</value>
      <webElementGuid>965b8aa1-bf0d-4011-acce-91ec81191199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cell value has been edited'])[12]/preceding::span[3]</value>
      <webElementGuid>d34681b2-fad1-4ba5-ab71-c4feb643b8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>6575734c-b352-4342-a069-5209abe378a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a/span/span/span[2]</value>
      <webElementGuid>e461b91f-1542-47c9-9536-ea7076afeda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_AdvancedFilter1_btnAdd-btnInnerEl' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>aefe95e0-1164-4891-a473-9dea5469b0ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
