<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2000</name>
   <tag></tag>
   <elementGuidId>63d0e3f7-5857-4111-9b78-d7af060cf6c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.x-monthpicker-item.x-monthpicker-year > a.x-monthpicker-item-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monthpicker-1017-yearEl']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a57b0c64-90e8-4be7-b831-68fac8fc010d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b86dce2c-ca8f-4985-9828-d2ac29b4672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-item-inner</value>
      <webElementGuid>cd759c97-6afb-4e2d-9907-9679ce70fdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01605473-90c0-4323-84f5-32fcc86c6cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>88c668fd-876d-49a2-932e-7275ae0ae3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-yearEl&quot;)/div[@class=&quot;x-monthpicker-item x-monthpicker-year&quot;]/a[@class=&quot;x-monthpicker-item-inner&quot;]</value>
      <webElementGuid>36e007d1-b8f0-40b3-9088-d35c8382d9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>5b788079-2915-46b7-90ab-8ea0f4d9d1d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div[2]/a</value>
      <webElementGuid>da8f2137-55db-48ba-bbd3-46a95142f182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2000')]</value>
      <webElementGuid>821359a5-9637-4b6f-ac46-15432227ebb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/following::a[3]</value>
      <webElementGuid>19ce54e8-3385-47a0-8107-dd6d84506467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun'])[1]/following::a[4]</value>
      <webElementGuid>06fabb1e-fb30-4618-bc83-1d6b0f1ef463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::a[10]</value>
      <webElementGuid>65da59bf-6437-45af-a0d3-5c966c46c10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[11]</value>
      <webElementGuid>67a369b3-3f91-4224-9eaf-25dedf4d076e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2000']/parent::*</value>
      <webElementGuid>42a07543-4327-4124-92ec-f4a00dd7ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>411ef8f0-7fdf-4395-865a-c08b0bb427f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '2000' or . = '2000')]</value>
      <webElementGuid>31071829-a9d1-48aa-8392-110ebcbb040f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
