<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dec_monthpicker-1017-prevEl</name>
   <tag></tag>
   <elementGuidId>5a97be68-7bd9-4978-8950-1d26bedeb72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthpicker-1017-prevEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='monthpicker-1017-prevEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b48cd689-91bb-414b-93b1-aad8ac509d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthpicker-1017-prevEl</value>
      <webElementGuid>92eb803c-bfda-4f7b-82af-3c23d20555a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>prevEl</value>
      <webElementGuid>7e5bdfdb-2e63-47d3-9c66-77a39c400b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-yearnav-button x-monthpicker-yearnav-prev x-unselectable x-monthpicker-yearnav-prev-over</value>
      <webElementGuid>f8b70bd1-6ca8-4afe-bfcd-d303db90049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b08e270f-abc7-4f44-8a1b-8f914f501290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ebc2ade-1bee-4072-aeb3-6380e8e3fdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-prevEl&quot;)</value>
      <webElementGuid>77f8589d-dd3b-4213-a27a-61f356d5325a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>067bdd4d-1b6f-42c9-b61e-6a2756c83fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='monthpicker-1017-prevEl']</value>
      <webElementGuid>dfe03895-2129-4f0e-adab-5e4fc53902c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div/div/a</value>
      <webElementGuid>c16c3281-6e07-4028-b947-6eee063645a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>4d3f0748-2b47-4ff5-8b54-8c2a3d930e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'monthpicker-1017-prevEl']</value>
      <webElementGuid>ac55ca6d-148d-4d15-86ba-35baa6c2061d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
