<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sep</name>
   <tag></tag>
   <elementGuidId>2640ad66-4cf5-4a25-8f06-2be22706ba29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.x-monthpicker-item-inner.x-monthpicker-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monthpicker-1017-monthEl']/div[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b535e71c-800b-4ec8-b16f-e57628655a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcdf4477-7c5e-4acf-be19-1741a3433d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>62fa0f46-f1cb-4513-b85f-51a46589e05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-item-inner x-monthpicker-selected</value>
      <webElementGuid>c7229675-9d08-4a99-9c38-03d6a6d72bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sep</value>
      <webElementGuid>75e014ab-dcf4-46d8-a55c-9cbae0a97056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-monthEl&quot;)/div[@class=&quot;x-monthpicker-item x-monthpicker-month&quot;]/a[@class=&quot;x-monthpicker-item-inner x-monthpicker-selected&quot;]</value>
      <webElementGuid>36adf2fe-1570-419f-8a18-830e2cf088f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>f154d58f-1c65-43ab-9544-922c4ff1ca0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-monthEl']/div[6]/a</value>
      <webElementGuid>3a6add83-bdcd-4a57-9ba0-b9b2d38a37a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sep')]</value>
      <webElementGuid>91c2e46c-6a6a-4dba-818b-3ab9b31bd2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar'])[1]/following::a[1]</value>
      <webElementGuid>b49542e5-78ab-416d-a0d0-7d4884747540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug'])[1]/following::a[2]</value>
      <webElementGuid>2848f1fd-c25d-4f99-b0ca-100f38061194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/preceding::a[1]</value>
      <webElementGuid>6947b834-e4fc-4d16-87f8-84acf780007b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct'])[1]/preceding::a[2]</value>
      <webElementGuid>98eb7c51-7504-4bd9-8b37-67f811331e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sep']/parent::*</value>
      <webElementGuid>bb680d2a-ce0f-4938-85f8-be2a5e2249a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>9f6f436d-d0ac-4682-a2f4-9a87163fd4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Sep' or . = 'Sep')]</value>
      <webElementGuid>24e05213-c50f-48d4-91d9-4a5b3f3b3856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
