<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dec_x-monthpicker-yearnav-button-ct</name>
   <tag></tag>
   <elementGuidId>8a1830cd-6ba7-408f-80e4-b45beef88469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.x-monthpicker-yearnav-button-ct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monthpicker-1017-yearEl']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9afa250b-621a-42b9-b41b-2875d50a30eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-monthpicker-yearnav-button-ct</value>
      <webElementGuid>5b155d2e-3511-425b-ae94-e4a2e09cf17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthpicker-1017-yearEl&quot;)/div[@class=&quot;x-monthpicker-yearnav&quot;]/div[@class=&quot;x-monthpicker-yearnav-button-ct&quot;]</value>
      <webElementGuid>bb161ad2-d650-448c-bebd-97dcdb68ee49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>7d5e5821-68d2-4db9-973e-18dc52dbab4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthpicker-1017-yearEl']/div/div</value>
      <webElementGuid>5c66759d-296c-410b-a167-2e99ff61ed50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/following::div[3]</value>
      <webElementGuid>ef55432b-b825-4af4-aa2c-3870cce672d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun'])[1]/following::div[4]</value>
      <webElementGuid>4907f9f7-b699-4b48-bc12-98648e88ec10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[13]</value>
      <webElementGuid>bde7c27f-12e9-4b9e-9b3d-23336e27a09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::div[13]</value>
      <webElementGuid>2e656e3b-768c-427a-ba82-5f87b0b97a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>50120808-50b0-4a33-85b4-3be9415ef015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
