<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__FK_District_Code-trigger-picker</name>
   <tag></tag>
   <elementGuidId>f9625697-61b2-43dc-8849-ed00541418f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FK_District_Code-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FK_District_Code-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19dba23e-00cb-4c11-9a9b-c683fdb371a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FK_District_Code-trigger-picker</value>
      <webElementGuid>366623f1-4af5-45de-845d-a23953b5834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-focus x-form-trigger-over</value>
      <webElementGuid>718dd594-2659-4c30-9f79-20b835879e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9e708640-1077-449d-9e16-2aaa111a3134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FK_District_Code-trigger-picker&quot;)</value>
      <webElementGuid>fb049cd3-4d35-4280-bf7a-bfbff55f3310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>5ff5c1f1-fa62-4179-8daa-0c9698a48527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='FK_District_Code-trigger-picker']</value>
      <webElementGuid>ac92164b-c902-48c7-8c63-40e3d904624b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FK_District_Code-triggerWrap']/div[3]</value>
      <webElementGuid>104dde2a-4a98-4d07-ba87-6d53593a925e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]</value>
      <webElementGuid>1a213e76-9229-46ad-8659-d30109d68ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'FK_District_Code-trigger-picker']</value>
      <webElementGuid>e55f17b4-3047-4ba0-a23b-135fc6309c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
