<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , Date_Birth-picker-prevEl,_aa5833</name>
   <tag></tag>
   <elementGuidId>458fb83b-91b1-44e5-9324-c13721e98feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-picker-prevEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Date_Birth-picker-prevEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80fade4f-1b85-406d-8cf6-2b6e56de0de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Birth-picker-prevEl</value>
      <webElementGuid>7decee5b-1378-47f5-a07c-c67d0ef7a83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>prevEl</value>
      <webElementGuid>3e34db34-9cf4-4970-b0d6-e23a4c51e91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-datepicker-prev x-datepicker-arrow x-unselectable</value>
      <webElementGuid>0150fbbf-de20-457d-a790-f40fb7c38621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e1c9eceb-3063-42a7-bbc5-1c2fa25bec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Previous Month (Control+Left)</value>
      <webElementGuid>7c057a2e-8b19-4dea-adc6-769635baae33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-picker-prevEl&quot;)</value>
      <webElementGuid>f9703144-a88e-4d80-af57-ec81d63393c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>2bbdc5b8-08c2-41b6-aa81-b1180fc156ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-picker-prevEl']</value>
      <webElementGuid>e62d3eb3-fc42-4892-9d06-4e998051f8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-picker-innerEl']/div/div</value>
      <webElementGuid>fc536a81-73e0-42af-932c-532649b8acb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[5]/div/div/div</value>
      <webElementGuid>8f214038-7dcd-46be-8aab-ae848605eb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Date_Birth-picker-prevEl' and @title = 'Previous Month (Control+Left)']</value>
      <webElementGuid>8b95fcd3-fa7e-4f4f-8452-04155d6e4972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
