<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ContentPlaceHolder1_FK_Multi_District__f3e468</name>
   <tag></tag>
   <elementGuidId>171b809d-42d3-47cb-81e9-389e9a28d56f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e7c54e6-d416-43ee-b42a-578cf9b7daad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker</value>
      <webElementGuid>d55cc1ad-ca2d-490d-ba99-3b44f5a60237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-simplearrowdown-trigger x-form-simplearrowdown-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>2b009cb8-1eee-4a69-bf8a-cf96ba6b9466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c5d5c098-d023-4437-b299-747720b12ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker&quot;)</value>
      <webElementGuid>149ddddb-2f88-4fb8-918f-1f5de81ee224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>d88370d1-bfae-4e83-add2-c24630809ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>b819f9cf-82ad-4985-902b-8a7a084425e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-triggerWrap']/div[3]</value>
      <webElementGuid>bfdddb35-9f37-4dfc-8d30-b7eb40e2c9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>ccdc2af1-58bb-44f5-ba76-93b3a8e9b9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ContentPlaceHolder1_FK_Multi_District_Code_ComboBox1-trigger-picker']</value>
      <webElementGuid>9be40ffb-d96a-4964-8036-da135d58a979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
