<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__Date_Birth-trigger-picker</name>
   <tag></tag>
   <elementGuidId>b71b6eeb-b3e8-4270-9d17-1995dcf61805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Date_Birth-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Date_Birth-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dacc3010-ce71-4bc3-b459-9b8855323344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Date_Birth-trigger-picker</value>
      <webElementGuid>25b73f29-7b9d-4eaa-ae1c-1a5c30e428a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-date-trigger x-form-date-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>da3e97f8-f22b-4a3e-ab76-27547fa2fb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a3eb72ae-3065-40ef-8750-d2690e731205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Date_Birth-trigger-picker&quot;)</value>
      <webElementGuid>8d6ff977-8ab1-4ac3-91f4-d6c9b2adff5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>63f7e55b-f0ef-4b5c-8747-e0737cee3bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-trigger-picker']</value>
      <webElementGuid>0a0184a0-d68f-4a3c-94d1-211d71fc70de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Date_Birth-triggerWrap']/div[2]</value>
      <webElementGuid>cf38bc50-b27b-4b6f-ae86-8c2ff6b13694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>8f5177f8-a78e-472f-9461-2b6756da5ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Date_Birth-trigger-picker']</value>
      <webElementGuid>b6ed853c-349a-43b3-93a4-74e88fadd011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
