<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View_nodeundefined_IFrame</name>
   <tag></tag>
   <elementGuidId>df081dc6-46fb-4410-b9a8-f989041ffdbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1029</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1029']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>75f03989-9637-43cf-ae1b-dc8cb75a197a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-component-default</value>
      <webElementGuid>3ced982a-97f8-4d19-ae5d-e440b2eaff7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1029</value>
      <webElementGuid>53ca1e5d-7349-4479-9c94-5c871377bb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nodeundefined_IFrame</value>
      <webElementGuid>c9a46e68-7816-4a59-a47e-b6e0c7b316b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707367988668</value>
      <webElementGuid>fcd1ed7d-8956-4390-820b-ce6f5113fdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7cb2f47-26f1-4a18-83b1-76fdbd98dae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1029&quot;)</value>
      <webElementGuid>358c3fe2-6a22-475b-bb32-befe5a83dfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1029']</value>
      <webElementGuid>12351751-c0ec-4d7e-8bd7-64fccf82e324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nodeundefined-body']/iframe</value>
      <webElementGuid>a68e2e85-1a76-4874-b7df-fafa44e56620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7a0d942f-9c89-4119-be65-e86605a64856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1029' and @name = 'nodeundefined_IFrame' and @src = '/NFQA_Test/parameter/parameterview.aspx?ModuleID=//dy0Uh5l6Ac0KaA+O/++U5064WYy6t86++ya2ldC7o=&amp;_dc=1707367988668']</value>
      <webElementGuid>3c69210b-5afb-4c0a-871d-9337dbb7d788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
