<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_September 2023</name>
   <tag></tag>
   <elementGuidId>0a97c237-34a0-4db1-9347-47d504d586d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#splitbutton-1014-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3a14e06-713b-4506-ad32-6d31b5adccd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splitbutton-1014-btnInnerEl</value>
      <webElementGuid>0ba37515-f867-4b72-8c2b-5cad597f5787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>945f8eb2-9ec9-4621-9ef0-566675c7989e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3e88868d-03ee-4376-b28a-ba2e6b585e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-small</value>
      <webElementGuid>8601302f-9cf4-4999-b1a3-f9399884a691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>September 2023</value>
      <webElementGuid>08472596-68c6-45da-b89f-bbfc9f8d2980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splitbutton-1014-btnInnerEl&quot;)</value>
      <webElementGuid>05ce5ee3-81dc-4a32-a205-016962a6667b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>f373e24a-06d6-4b05-865b-83a9a96dbe07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnInnerEl']</value>
      <webElementGuid>72f8c9e4-e728-4213-a2da-b5ffd44bd1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='splitbutton-1014-btnEl']/span[2]</value>
      <webElementGuid>9e10065b-f76a-4dff-836e-25c71d79ea7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'splitbutton-1014-btnInnerEl', '&quot;', ')')])[1]/following::span[4]</value>
      <webElementGuid>e35e39f5-3b0d-4f4a-9592-0fc8792b0241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a month (Control+Up/Down to move years)'])[1]/following::span[4]</value>
      <webElementGuid>dde90950-36f5-4373-8114-acabd6d55e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::span[2]</value>
      <webElementGuid>f1c8ef9d-3da2-4b7d-a5bd-c1516756b4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::span[2]</value>
      <webElementGuid>8333d9d4-9343-4c29-aae3-7ce238a8f478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='September 2023']/parent::*</value>
      <webElementGuid>c5c02fde-9695-4e83-ad05-fd94cdab3c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span/span/span[2]</value>
      <webElementGuid>8fe2f355-9126-4cf3-8253-929a5a7c0779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'splitbutton-1014-btnInnerEl' and (text() = 'September 2023' or . = 'September 2023')]</value>
      <webElementGuid>bf93e950-4ac3-4ffa-9e1d-d2a875680698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
