<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cell value has been edited_x-grid-checkcolumn</name>
   <tag></tag>
   <elementGuidId>dd1a4cfe-6804-4973-aa35-a44a86a3c332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[6]/div[2]/div/div/div/div[2]/div[1]/div[2]/table[1]/tbody/tr/td[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_LblConfirmation-textEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b30b1590-efb3-4543-878f-f69418be4e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_LblConfirmation-textEl</value>
      <webElementGuid>d9e14ef1-0ab9-458e-8b44-ce78cb937b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>a4db4a9b-15d0-4895-9632-92f95b163850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-label-value</value>
      <webElementGuid>4788c19c-eab0-4294-8a53-a785f40f61af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Saved into Database.</value>
      <webElementGuid>777b909e-c1ad-4503-8728-0bdc23eff103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_LblConfirmation-textEl&quot;)</value>
      <webElementGuid>1b127690-36a9-471a-a59c-823b13957356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>671361fe-8182-4a73-886e-96ef665fdaf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_LblConfirmation-textEl']</value>
      <webElementGuid>5bfc44df-05c7-45a5-8f2f-b6a8dff508d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='ContentPlaceHolder1_LblConfirmation']/span</value>
      <webElementGuid>adedbed3-3bf3-44a2-b708-e887ca30b3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::span[2]</value>
      <webElementGuid>0cbf4f80-396c-48ef-94dd-af5af77ca204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[3]</value>
      <webElementGuid>179ca24f-426a-450c-aabe-b2fd681ff677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Engineer Transaction Add'])[1]/preceding::span[8]</value>
      <webElementGuid>67fc95fc-5ffb-489a-a6ab-d33a53f1a27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data Saved into Database.']/parent::*</value>
      <webElementGuid>0a40d591-0818-4fb9-aa89-586c628c809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>aed929fe-ead9-4520-b382-b83d8423aa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_LblConfirmation-textEl' and (text() = 'Data Saved into Database.' or . = 'Data Saved into Database.')]</value>
      <webElementGuid>9506caa2-6656-4012-b025-7d747ea805d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
