<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add New Record</name>
   <tag></tag>
   <elementGuidId>46a47e22-7136-4f07-b5e1-63d2ab642c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnAdd-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BtnAdd-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91c4455e-9b00-4503-81bc-95b148de5b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnAdd-btnInnerEl</value>
      <webElementGuid>4c4a7a45-db47-4be0-8b10-4dbab4834f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>fd29458a-9428-4cfd-9331-b1a07d6d1fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>09197f91-9e6d-41bd-99aa-4d380750aa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>411d7f55-419a-4e0b-855a-0d1924820836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Record</value>
      <webElementGuid>3e9f81bb-1e7a-400c-960b-0d3ff56c86bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnAdd-btnInnerEl&quot;)</value>
      <webElementGuid>360c5c55-bfdf-4640-b886-4eabfd60caef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add New Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>d4e036c6-bc35-44fd-a24c-b59ca0b77c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BtnAdd-btnInnerEl']</value>
      <webElementGuid>1ab1d0de-00bf-45fd-b2aa-c9e33986873f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='BtnAdd-btnEl']/span[2]</value>
      <webElementGuid>19463efc-36eb-49ab-b9fa-b5e93d5f48eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export All Page'])[1]/following::span[4]</value>
      <webElementGuid>cc68b62c-0eaa-4420-a9c6-75dcaf18fc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Current Page'])[1]/following::span[8]</value>
      <webElementGuid>5ea8717d-ebab-4236-84c6-1d58b280dd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Filter'])[1]/preceding::span[2]</value>
      <webElementGuid>96e7d2d3-ab5a-49f6-91a7-5c3b5122b6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Advanced Filter'])[1]/preceding::span[11]</value>
      <webElementGuid>90d2b4a4-28e1-4d4f-8914-ba81e7389a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Record']/parent::*</value>
      <webElementGuid>4f6bafe7-33c3-478f-a1dc-9a9193480be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span/span/span[2]</value>
      <webElementGuid>36cca694-0f29-4360-834c-9e72cb2efd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BtnAdd-btnInnerEl' and (text() = 'Add New Record' or . = 'Add New Record')]</value>
      <webElementGuid>07728b4c-097f-4610-8da6-fec7cefc1568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
