<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Engineer Test_x-tree-elbow-img x-tree-e_ddfa71</name>
   <tag></tag>
   <elementGuidId>ccdf447d-e3e7-4814-9ed8-46599f941fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ext-element-14']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09c2c36e-fbc1-401e-ac55-07774b6a571d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> x-tree-elbow-img x-tree-elbow-end-plus x-tree-expander</value>
      <webElementGuid>0352aa7b-bc8b-4c8b-a415-a4d22e00696a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5456e5c1-e811-4283-abb7-acd07651f091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-14&quot;)/div[@class=&quot;x-grid-cell-inner x-grid-cell-inner-treecolumn&quot;]/div[@class=&quot;x-tree-elbow-img x-tree-elbow-end-plus x-tree-expander&quot;]</value>
      <webElementGuid>96aa69ff-8844-41d9-a08c-3901d17d25c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ext-element-14']/div/div[2]</value>
      <webElementGuid>cf225549-89df-4e72-aeeb-8e4a6f60861c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/div/div[2]</value>
      <webElementGuid>88fa13b2-9c07-454d-bf47-2ea5ec205a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
