<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cell value has been edited_ext-element-20</name>
   <tag></tag>
   <elementGuidId>50bc7f14-b0a1-4099-a13d-88d38b0eea5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-element-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ext-element-20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1c4a138-0999-4773-b9d1-325075893f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-clear-button</value>
      <webElementGuid>06739734-c673-41a6-a91f-88e2b10b5aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-20</value>
      <webElementGuid>aeeab588-3719-454e-b0b8-47c1a89d852f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-20&quot;)</value>
      <webElementGuid>b8acb01d-5734-4562-8c3f-7094e19a7856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Search Function/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>d5a666d0-297d-40c9-b152-6f13248bd608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-element-20']</value>
      <webElementGuid>7a08251b-4ac8-41ad-8470-242caa343fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textfield-1029-bodyEl']/div[2]</value>
      <webElementGuid>daebd1d2-136b-4053-88d0-25e61138f2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>879ba799-5fba-4dbb-b629-67f79d167d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-element-20']</value>
      <webElementGuid>300243b1-f92f-4e91-9ebf-dcce6b3e5715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
