<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cell value has been edited_ext-element-12</name>
   <tag></tag>
   <elementGuidId>ede53e99-b15c-4e21-a2f0-337e7a35d841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-element-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ext-element-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a11bce89-c806-4e34-8cbf-2647db608fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-clear-button</value>
      <webElementGuid>fc5b415e-d05e-4e33-a0bc-4d1e64ebd339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-12</value>
      <webElementGuid>e4398310-6d24-4a7f-819d-05762019d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-12&quot;)</value>
      <webElementGuid>8a429ae7-689e-40fe-8001-0c1db82a44f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Search Function/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>30618c6a-ba5e-47da-b35c-dc26599d9732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-element-12']</value>
      <webElementGuid>1b599d3c-b0f9-48a7-ae03-5d53f84144d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textfield-1018-bodyEl']/div[2]</value>
      <webElementGuid>ef778b14-7a29-4ecc-a22a-e1c2f0c9c16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>04872039-36fc-4474-99a8-479fd11f4438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-element-12']</value>
      <webElementGuid>03739012-7755-46dd-9056-440621439644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
