<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Engineer Test_x-tree-elbow-img x-tree-e_ddfa71</name>
   <tag></tag>
   <elementGuidId>2fe74e89-b2f2-4f50-bebd-5b64ef230372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='ext-element-14']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19d9a31a-8aa6-42f0-8d75-668683953cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> x-tree-elbow-img x-tree-elbow-end-plus x-tree-expander</value>
      <webElementGuid>e30761df-4361-4346-b872-4c98f47e3e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>47136b6d-151f-4dcb-9edd-24ff02e1fb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-14&quot;)/div[@class=&quot;x-grid-cell-inner x-grid-cell-inner-treecolumn&quot;]/div[@class=&quot;x-tree-elbow-img x-tree-elbow-end-plus x-tree-expander&quot;]</value>
      <webElementGuid>65ef9fca-a3d3-4a8c-be4b-0490cc3e198d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ext-element-14']/div/div[2]</value>
      <webElementGuid>e42e37b5-768a-4378-93be-16e22b2a5ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/div/div[2]</value>
      <webElementGuid>c7d32838-1c4e-44e8-bfbb-4533aefc9824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
