<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_No Data Changes</name>
   <tag></tag>
   <elementGuidId>eca57dc4-aa1c-4ea6-9f2c-82029346ca6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div[1]/div/div/div[1]/div/div/div[2]/div/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_LblConfirmation-textEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>889ffe5b-ced2-4a13-85df-2baaa6695de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_LblConfirmation-textEl</value>
      <webElementGuid>cfc5e21e-d3a2-46e1-a28a-17a9f41c8c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>7aa4d372-55a1-444a-a744-c064d11e34df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-label-value</value>
      <webElementGuid>374aeb5e-1220-408f-bbff-e66b37de2516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data Saved into Database.</value>
      <webElementGuid>afac103e-25f3-4449-bbbd-037ac353cf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_LblConfirmation-textEl&quot;)</value>
      <webElementGuid>3b41d062-2c9c-41a4-8dd4-3ccf5c430989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Edit Record/Page_/iframe_View_nodeundefined_IFrame</value>
      <webElementGuid>6d438f16-64df-4285-befb-48e03bbb5a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_LblConfirmation-textEl']</value>
      <webElementGuid>5c5011a0-bc69-4d02-9be5-ced7a81518ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='ContentPlaceHolder1_LblConfirmation']/span</value>
      <webElementGuid>98a43f4f-7362-496f-ac47-3e2bc06b8d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::span[2]</value>
      <webElementGuid>acd0267e-f8c1-4d42-9926-8a188a895d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::span[3]</value>
      <webElementGuid>6082e465-ee30-4238-ba4c-1c79406f0f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Engineer Transaction Edit'])[1]/preceding::span[8]</value>
      <webElementGuid>27571b07-9399-4f09-b7a4-650ba7be5c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data Saved into Database.']/parent::*</value>
      <webElementGuid>a63b026c-62a7-4b2a-876e-81ceb6de94cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>fafb3adc-7021-4f25-af1e-98f79f4aa7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_LblConfirmation-textEl' and (text() = 'Data Saved into Database.' or . = 'Data Saved into Database.')]</value>
      <webElementGuid>773fca8c-a89c-4e2f-a3ea-c3ab41860d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
